### ISSUE TITLE
Backtest Not run with SMA

### ISSUE THREAD

**Issue by kernelhacks** [trentstauff/FXBot#32]
Traceback (most recent call last):
  File "main.py", line 214, in <module>
    trader = SMABacktest(instrument, start, end, smas, smal, granularity, trading_cost)
  File "/root/FXBot/backtesting/SMABacktest.py", line 25, in __init__
    super().__init__(
  File "/root/FXBot/backtesting/Backtester.py", line 27, in __init__
    self._data = self.acquire_data()
  File "/root/FXBot/backtesting/Backtester.py", line 41, in acquire_data
    df = oanda.get_history(
  File "/root/FXBot/env/lib/python3.8/site-packages/tpqoa-0.0.55-py3.8.egg/tpqoa/tpqoa.py", line 241, in get_history
AttributeError: 'Index' object has no attribute 'tz_localize'

**Comment by kernelhacks** [comment]
Sorry to reopen this issue but the command do not work, I don't know way after I run that command was working but when I stop the bot and run again I get the same error again. AttributeError: 'Index' object has no attribute 'tz_localize'

**Comment by kernelhacks** [comment]
Ok, it looks that the issue only appears when the start and the end date are the same.
but when I was playing with the SMAS and the SMAL and the granularity, some combinations produce errors.

**Comment by kernelhacks** [comment]
this backtest setup work 
EUR_USD
Live Trading (1) or Backtesting (2)? 
2
Please choose the strategy you would like to backtest: 

sma, bollinger_bands, contrarian, momentum, ml_classification, ml_regression, 
sma
Enter the start date for the backtest (string, in form of "YYYY-MM-DD"): 

2022-04-19
Enter the end date for the backtest (string, in form of "YYYY-MM-DD"): 

2022-04-20
Enter the trading cost to consider: (float, IE 0.0, 0.00007): 

1.0811
Please enter the granularity for your session (See list in README, IE "S30", "M1", "H1"): 

M1
Enter SMAS value (integer, IE 9): 

7
Enter SMAL value (integer, IE 20): 

18
Downloading historical data...
Download complete.
Testing strategy with smas = 7, smal = 18 ...
Return: -100.0%, Out Performance: -100.11%
Optimizing strategy...
25%...
50%...
75%...
Strategy optimized on interval 2022-04-19 - 2022-04-20
Max Return: -100.0%, Best SMAS: 34 (M1), Best SMAL: 247 (M1)
Plotting Results.

**Comment by kernelhacks** [comment]
I think I found the issue only works with granularity M1 or S30

**Comment by trentstauff** [comment]
Interesting. Ill take a look
