### ISSUE TITLE
AttributeError: 'BollingerBandsLive' object has no attribute '_position'

### ISSUE THREAD

**Issue by milandijhon** [trentstauff/FXBot#37]
i been getting this issue all day. everything was fine last night.

Traceback (most recent call last):
  File "C:\Users\BNard\Documents\GitHub\FXBot-main\FXBot-main\main.py", line 143, in <module>
    trader = BollingerBandsLive(cfg, instrument, granularity, sma, deviation, units, stop_loss=stop_loss,
  File "C:\Users\BNard\Documents\GitHub\FXBot-main\FXBot-main\livetrading\BollingerBandsLive.py", line 37, in __init__
    super().__init__(
  File "C:\Users\BNard\Documents\GitHub\FXBot-main\FXBot-main\livetrading\LiveTrader.py", line 45, in __init__
    raise Exception("Sorry, markets are closed")
Exception: Sorry, markets are closed
Exception ignored in: <function LiveTrader.__del__ at 0x00000242455913F0>
Traceback (most recent call last):
  File "C:\Users\BNard\Documents\GitHub\FXBot-main\FXBot-main\livetrading\LiveTrader.py", line 82, in __del__
    self.close_position()
  File "C:\Users\BNard\Documents\GitHub\FXBot-main\FXBot-main\livetrading\LiveTrader.py", line 257, in close_position
    if self._position != 0:
AttributeError: 'BollingerBandsLive' object has no attribute '_position'

**Comment by trentstauff** [comment]
Will look into this too.
