### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

### ISSUE THREAD

**Issue by milandijhon** [trentstauff/FXBot#38]
getting the following error:   Traceback (most recent call last):
  File "C:\Users\Administrator\GitHub\FXBot-main\FXBot-main\main.py", line 143, in <module>
    trader = BollingerBandsLive(cfg, instrument, granularity, sma, deviation, units, stop_loss=stop_loss,
  File "C:\Users\Administrator\GitHub\FXBot-main\FXBot-main\livetrading\BollingerBandsLive.py", line 37, in __init__
    super().__init__(
  File "C:\Users\Administrator\GitHub\FXBot-main\FXBot-main\livetrading\LiveTrader.py", line 77, in __init__
    self.stream_data(self._instrument)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tpqoa\tpqoa.py", line 357, in stream_data
    self.on_success(msg.time,
  File "C:\Users\Administrator\GitHub\FXBot-main\FXBot-main\livetrading\LiveTrader.py", line 181, in on_success
    self._tick_data = self._tick_data.append(df)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

**Comment by Fishball99** [comment]
I have the same problem, waiting for the answer

**Comment by trentstauff** [comment]
Hi there- I will look into this!

Trent

**Comment by Fishball99** [comment]
I think this error comes from the most recent update of pandas so that there may be some incompatible problems. I have rolled back the pandas to previous version, then it goes well.

**Comment by milandijhon** [comment]
Trent,
  now getting this error, can you help? I installed on 3 different machines, fresh installs and getting errors. if you can, can you try a fresh install to see the issues?    error below:   Instrument: EUR_USDLive Trading (1) or Backtesting (2)?1Please choose the strategy you would like to utilize: 
sma, bollinger_bands, contrarian, momentum, ml_classification,bollinger_bandsPlease enter the granularity for your session (NOT from list in README, try "1hr", "1m", "30s" (less strict):
1mPlease enter the number of units you'd like to trade with (integer, IE 200000 units): 
10000Enter stop profit dollars to halt trading at (float, IE 25, 15.34, etc)  (enter "n" if not applicable): 
100Enter a negative stop loss to halt trading at (float, IE -25, -1.32, etc) (enter "n" if not applicable): 
-10Enter SMA value (integer, IE 9): 
50Enter deviation value (integer, IE 2): 
2Markets are open, beginning trading session.Setting up history...Traceback (most recent call last):  File "C:\Users\BNard\Documents\GitHub\FXBot\main.py", line 143, in <module>    trader = BollingerBandsLive(cfg, instrument, granularity, sma, deviation, units, stop_loss=stop_loss,     File "C:\Users\BNard\Documents\GitHub\FXBot\livetrading\BollingerBandsLive.py", line 37, in __init__          super().__init__(    self.setup_history(history_days)  File "C:\Users\BNard\Documents\GitHub\FXBot\livetrading\LiveTrader.py", line 96, in setup_history    self.get_history(  File "C:\Users\BNard\Documents\GitHub\FXBot\venv\lib\site-packages\tpqoa-0.0.55-py3.10.egg\tpqoa\tpqoa.py", line 232, in get_history  File "C:\Users\BNard\Documents\GitHub\FXBot\venv\lib\site-packages\tpqoa-0.0.55-py3.10.egg\tpqoa\tpqoa.py", line 167, in retrieve_data  File "C:\Users\BNard\Documents\GitHub\FXBot\venv\lib\site-packages\v20-3.0.25.0-py3.10.egg\v20\response.py", line 35, in getv20.errors.ResponseNoField: 400 response for GET https://api-fxtrade.oanda.com:443/v3/instruments/EUR_USD/candles?price=M&granularity=S5&from=2023-04-20T09%3A01%3A59.000000000Z&to=2023-04-20T15%3A01%3A59.000000000Z does not have field 'candles' (contains 'errorMessage'
please help been down over a week.

    On Wednesday, April 19, 2023 at 09:36:36 PM GMT-5, Wenqin Yu ***@***.***> wrote:  
 
 


I think this error comes from the most recent update of pandas so that there may be some incompatible problems. I have rolled back the pandas to previous version, then it goes well.

**Comment by trentstauff** [comment]
Hi everyone. I am currently without my windows development machine for a few weeks. Once I return I plan on ironing out these bugs.

I apologize for the inconvenience!

**Comment by Terence-Wong** [comment]
It's been many months! when will you fix this?! thinking about un-starring...
